
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsiipvxohbnxetnwesrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzaWlwdnhvaGJueGV0bndlc3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjE0NzAsImV4cCI6MjA1NzkzNzQ3MH0.1l9P5826ope18LKzzCv-9YM1wxT1ic1Lz2c3xH7GAB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
